const config=window.VIBEFLEX_CONFIG||{};
const colors=['Charcoal','Deep Teal','Navy','Forest Green'];
const sizes=['S','M','L','XL','2XL','3XL'];
const variants=colors.flatMap(color=>sizes.map(size=>({color,size,sku:`490-UCPH-${color.replace(/\s/g,'').slice(0,4).toUpperCase()}-${size}`})));
function route(){const id=(location.hash||'#home').slice(1);document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===id));if(id==='store')loadStore();}
addEventListener('hashchange',route);route();
document.querySelector('#variant-grid').innerHTML=variants.map(v=>`<div><b>${v.color}</b><span>${v.size}</span><code>${v.sku}</code></div>`).join('');
async function invoke(action,payload={}){
 if(!config.supabaseUrl||config.supabaseUrl.includes('YOUR_PROJECT'))throw new Error('Supabase URL is not configured in config.js.');
 const r=await fetch(`${config.supabaseUrl}/functions/v1/integrations`,{method:'POST',headers:{'Content-Type':'application/json','apikey':config.supabaseAnonKey,'Authorization':`Bearer ${config.supabaseAnonKey}`},body:JSON.stringify({action,...payload})});
 const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||`Function failed (${r.status})`);return j;
}
const integrations=[
 {name:'Shopify',desc:'vibeflex-813.myshopify.com',action:'test-shopify',items:['Client ID + Secret exchanged server-side','Reads shop name and three products','Draft publishing stays owner-locked']},
 {name:'Printful',desc:'Catalog, variants, and mockups',action:'test-printful',items:['Private token stays server-side','Read-only store test','No order or paid mockup during test']},
 {name:'Airtable',desc:'Shopify Product Catalog',action:'test-airtable',items:['Base appuaF1jfeBr2PPqn','Table tbl7t3sguT93pYwbV','Reads three records without changes']}
];
document.querySelector('#connection-cards').innerHTML=integrations.map((x,i)=>`<section class="card connection"><div class="card-head"><div><span class="eyebrow">INTEGRATION</span><h2>${x.name}</h2><p>${x.desc}</p></div><span class="icon">⚡</span></div><ul>${x.items.map(v=>`<li>${v}</li>`).join('')}</ul><div id="connection-${i}" class="status">Not tested</div><button data-test="${i}">Test connection</button></section>`).join('');
document.querySelectorAll('[data-test]').forEach(btn=>btn.addEventListener('click',async()=>{const i=Number(btn.dataset.test),x=integrations[i],s=document.querySelector(`#connection-${i}`);btn.disabled=true;s.className='status';s.textContent='Testing securely…';try{const d=await invoke(x.action);s.className='status ok';s.textContent=d.message||'Connected';}catch(e){s.className='status error';s.textContent=e.message;}finally{btn.disabled=false;}}));
document.querySelector('#run-demo').addEventListener('click',async()=>{const b=document.querySelector('#run-demo'),s=document.querySelector('#workflow-status');b.disabled=true;s.className='status';s.textContent='Checking owner access…';try{const d=await invoke('run-hoodie-demo',{product:{title:'490 Uncooked Premium Hoodie',colors,sizes,variants}});s.className='status ok';s.textContent=d.message;}catch(e){s.className='status error';s.textContent=e.message;}finally{b.disabled=false;}});
let storeLoaded=false;
let storeLoading=false;
function storefrontConfigured(){return Boolean(config.shopifyDomain&&!String(config.shopifyDomain).includes('YOUR_')&&config.storefrontToken&&!String(config.storefrontToken).includes('YOUR_'));}
function showStoreRetry(message){const status=document.querySelector('#store-status'),target=document.querySelector('#products');status.className='status error';status.textContent=message;target.innerHTML='<button id="retry-store">Try again</button>';document.querySelector('#retry-store')?.addEventListener('click',()=>loadStore(true));}
async function loadStore(force=false){if(storeLoading||(!force&&storeLoaded))return;const status=document.querySelector('#store-status'),target=document.querySelector('#products');if(!storefrontConfigured()){storeLoaded=false;status.className='status';status.textContent='Store preview is not configured yet. Add the browser-safe Shopify Storefront token in config.js.';target.innerHTML='';return;}storeLoading=true;status.className='status';status.textContent='Loading products…';target.innerHTML='';try{const headers={'Content-Type':'application/json','X-Shopify-Storefront-Access-Token':config.storefrontToken};const r=await fetch(`https://${config.shopifyDomain}/api/2026-07/graphql.json`,{method:'POST',headers,body:JSON.stringify({query:`query { products(first:24, sortKey:CREATED_AT, reverse:true){nodes{id title handle featuredImage{url altText} priceRange{minVariantPrice{amount currencyCode}}}}}`})});const j=await r.json().catch(()=>({}));if(!r.ok||j.errors)throw new Error(j.errors?.[0]?.message||`Shopify failed (${r.status})`);const products=j.data?.products?.nodes||[];storeLoaded=true;status.className='status ok';status.textContent=`Loaded ${products.length} products.`;target.innerHTML=products.map(p=>`<article class="product">${p.featuredImage?`<img src="${p.featuredImage.url}" alt="${p.featuredImage.altText||p.title}">`:''}<h3>${p.title}</h3><p>$${p.priceRange.minVariantPrice.amount}</p><a href="https://${config.shopifyDomain}/products/${p.handle}" target="_blank" rel="noopener">View product</a></article>`).join('');}catch(e){storeLoaded=false;showStoreRetry(e instanceof Error?e.message:'Unable to load Shopify products.');}finally{storeLoading=false;}}
