const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
async function shopifyToken(){const shop=Deno.env.get('SHOPIFY_SHOP_DOMAIN');const id=Deno.env.get('SHOPIFY_CLIENT_ID');const secret=Deno.env.get('SHOPIFY_CLIENT_SECRET');if(!shop||!id||!secret)throw new Error('Shopify server secrets are incomplete.');const r=await fetch(`https://${shop}/admin/oauth/access_token`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({grant_type:'client_credentials',client_id:id,client_secret:secret})});if(!r.ok)throw new Error(`Shopify authentication failed (${r.status}).`);return (await r.json()).access_token as string;}
async function shopify(query:string,variables:Record<string,unknown>={}){const shop=Deno.env.get('SHOPIFY_SHOP_DOMAIN');const token=await shopifyToken();const r=await fetch(`https://${shop}/admin/api/2026-04/graphql.json`,{method:'POST',headers:{'Content-Type':'application/json','X-Shopify-Access-Token':token},body:JSON.stringify({query,variables})});const j=await r.json();if(!r.ok||j.errors)throw new Error(j.errors?.[0]?.message||`Shopify API failed (${r.status}).`);return j.data;}
async function testShopify(){const d=await shopify(`query { shop{name} products(first:3){nodes{id title}} }`);return {message:`Connected to ${d.shop.name}. Read ${d.products.nodes.length} products.`};}
async function testPrintful(){const token=Deno.env.get('PRINTFUL_TOKEN');if(!token)throw new Error('PRINTFUL_TOKEN is not configured.');const r=await fetch('https://api.printful.com/stores',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`Printful connection failed (${r.status}).`);const j=await r.json();return {message:`Connected to Printful. Found ${j.result?.length||0} store(s).`};}
async function testAirtable(){const token=Deno.env.get('AIRTABLE_TOKEN');const base=Deno.env.get('AIRTABLE_BASE_ID')||'appuaF1jfeBr2PPqn';const table=Deno.env.get('AIRTABLE_TABLE_ID')||'tbl7t3sguT93pYwbV';if(!token)throw new Error('AIRTABLE_TOKEN is not configured.');const r=await fetch(`https://api.airtable.com/v0/${base}/${table}?maxRecords=3`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`Airtable connection failed (${r.status}).`);const j=await r.json();return {message:`Connected to Airtable. Read ${j.records?.length||0} records.`};}
function validate(v:any[]){if(v.length!==24)throw new Error(`Expected 24 variants; received ${v.length}.`);if(new Set(v.map(x=>x.sku)).size!==24)throw new Error('Duplicate SKUs detected.');}
async function runDemo(product:any){validate(product.variants);const input={title:product.title,status:'DRAFT',productOptions:[{name:'Color',values:product.colors.map((name:string)=>({name}))},{name:'Size',values:product.sizes.map((name:string)=>({name}))}]};const d=await shopify(`mutation Create($product:ProductCreateInput!){productCreate(product:$product){product{id title status} userErrors{field message}}}`,{product:input});if(d.productCreate.userErrors?.length)throw new Error(d.productCreate.userErrors.map((e:any)=>e.message).join('; '));const p=d.productCreate.product;return {message:`Created Shopify DRAFT ${p.id}. All 24 SKUs validated. Bulk variant creation remains intentionally gated until the live mutation is verified.`};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const b=await req.json();if(b.action==='test-shopify')return reply(await testShopify());if(b.action==='test-printful')return reply(await testPrintful());if(b.action==='test-airtable')return reply(await testAirtable());if(b.action==='run-hoodie-demo')return reply(await runDemo(b.product));return reply({error:'Unknown action'},400);}catch(e){return reply({error:e instanceof Error?e.message:'Unknown error'},500);}});
